services:

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        image: frontendimg
        ports:
           -  3000:3000
        depends_on:
            - backend

    backend:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - SPRING_DATASOURCE_USER=postgres
            - SPRING_DATASOURCE_PASSWORD=postgres
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/test
        image: backendimg
        ports:
           -  9001:9001
        depends_on:
            - postgres

    postgres:
        container_name: postgres
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test
        ports:
            - '5433:5432'
        volumes:
           - postgres:/var/lib/postgresql/data


volumes:
   postgres:
