
name: Building and deploying services

on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - main

jobs:    
    build_and_push:
      runs-on: self-hosted
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          id: buildx
          uses: ./
          with:
            version: ${{ matrix.buildx-version }}

        - name: Login to dockerhub
          run: docker login -u "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"

        - name: Build and push images
          run: |
            docker-compose up -d
            docker tag frontendpp "${{secrets.DOCKER_USERNAME}}"/frontendapp
            docker tag backendapp "${{secrets.DOCKER_USERNAME}}"/backendapp
            docker push "${{secrets.DOCKER_USERNAME}}"/frontendapp
            docker push "${{secrets.DOCKER_USERNAME}}"/backendapp
